
services:
  remark42:
    image: umputun/remark42:latest
    container_name: remark42
    ports:
      - "8080:8080" # Puerto en el que estará disponible Remark42
    environment:
      - REMARK_URL=https://tdpblog.com.ar # Cambia esto a tu dominio
      - SITE=tdpblog.com.ar # Cambia esto también
      - SECRET=tdpblog1985 # Cambia a un valor seguro
      - ADMIN_SHARED_ID=${ADMIN_SHARED_ID} # ID de administrador (cámbialo)
      - CORS=true

      # proveedores de authenticación
      - AUTH_GITHUB_CLI_ID=${AUTH_GITHUB_CLI_ID}
      - AUTH_GITHUB_CLI_SECRET=${AUTH_GITHUB_CLI_SECRET}
      - AUTH_GOOGLE_CLI_ID=${AUTH_GOOGLE_CLI_ID}
      - AUTH_GOOGLE_CLI_SECRET=${AUTH_GOOGLE_CLI_SECRET} 


    volumes:
      - ./data:/srv/var # Carpeta donde se guardarán los datos
    restart: always

    
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"      # Puerto para tráfico HTTP
      - "443:443"    # Puerto para tráfico HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Monta el archivo de configuración de Nginx
      - ./ssl:/etc/nginx/ssl                   # Monta el directorio de certificados SSL
    depends_on:
      - remark42
    restart: always